version: '3.0'

services:
    nginx:
        image: nginx
        restart: always
        environment:
            - VIRTUAL_HOST=site.local
        depends_on:
            - php
        networks:
            - backend
        volumes:
            - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html/
            - ./log/nginx:/var/log/nginx
        ports:
            - 80:80
    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: fault_app
        container_name: fault
        restart: always
        volumes:
            - ./log/nginx:/var/log/nginx
        networks:
            - backend
        tty: true

networks:
    backend:
    